%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: DsLogAdmin_LogList
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('DsLogAdmin_LogList').
-ic_compiled("4_2_25").


-include("DsLogAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_sequence,{tk_objref,"IDL:omg.org/DsLogAdmin/Log:1.0","Log"},0}.

%% returns id
id() -> "IDL:omg.org/DsLogAdmin/LogList:1.0".

%% returns name
name() -> "DsLogAdmin_LogList".



