%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: DsLogAdmin
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(DSLOGADMIN_HRL).
-define(DSLOGADMIN_HRL, true).


-record('DsLogAdmin_InvalidParam', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidParam:1.0", details}).
-record('DsLogAdmin_InvalidThreshold', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidThreshold:1.0"}).
-record('DsLogAdmin_InvalidTime', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidTime:1.0"}).
-record('DsLogAdmin_InvalidTimeInterval', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidTimeInterval:1.0"}).
-record('DsLogAdmin_InvalidMask', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidMask:1.0"}).
-record('DsLogAdmin_LogIdAlreadyExists', {'OE_ID'="IDL:omg.org/DsLogAdmin/LogIdAlreadyExists:1.0"}).
-record('DsLogAdmin_InvalidGrammar', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidGrammar:1.0"}).
-record('DsLogAdmin_InvalidConstraint', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidConstraint:1.0"}).
-record('DsLogAdmin_LogFull', {'OE_ID'="IDL:omg.org/DsLogAdmin/LogFull:1.0", n_records_written}).
-record('DsLogAdmin_LogOffDuty', {'OE_ID'="IDL:omg.org/DsLogAdmin/LogOffDuty:1.0"}).
-record('DsLogAdmin_LogLocked', {'OE_ID'="IDL:omg.org/DsLogAdmin/LogLocked:1.0"}).
-record('DsLogAdmin_LogDisabled', {'OE_ID'="IDL:omg.org/DsLogAdmin/LogDisabled:1.0"}).
-record('DsLogAdmin_InvalidRecordId', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidRecordId:1.0"}).
-record('DsLogAdmin_InvalidAttribute', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidAttribute:1.0", attr_name, value}).
-record('DsLogAdmin_InvalidLogFullAction', {'OE_ID'="IDL:omg.org/DsLogAdmin/InvalidLogFullAction:1.0"}).
-record('DsLogAdmin_NVPair', {name, value}).
-record('DsLogAdmin_TimeInterval', {start, stop}).
-record('DsLogAdmin_LogRecord', {id, time, attr_list, info}).
-record('DsLogAdmin_AvailabilityStatus', {off_duty, log_full}).
-record('DsLogAdmin_Time24', {hour, minute}).
-record('DsLogAdmin_Time24Interval', {start, stop}).
-record('DsLogAdmin_WeekMaskItem', {days, intervals}).
-record('DsLogAdmin_UnsupportedQoS', {'OE_ID'="IDL:omg.org/DsLogAdmin/UnsupportedQoS:1.0", denied}).


-endif.


