%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: DsLogAdmin_LogMgr
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(DSLOGADMIN_LOGMGR_HRL).
-define(DSLOGADMIN_LOGMGR_HRL, true).




-endif.


