%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: DsLogAdmin_TimeInterval
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('DsLogAdmin_TimeInterval').
-ic_compiled("4_2_25").


-include("DsLogAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_struct,"IDL:omg.org/DsLogAdmin/TimeInterval:1.0","TimeInterval",
                   [{"start",tk_ulonglong},{"stop",tk_ulonglong}]}.

%% returns id
id() -> "IDL:omg.org/DsLogAdmin/TimeInterval:1.0".

%% returns name
name() -> "DsLogAdmin_TimeInterval".



