%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: DsLogAdmin_AvailabilityStatus
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('DsLogAdmin_AvailabilityStatus').
-ic_compiled("4_2_25").


-include("DsLogAdmin.hrl").

-export([tc/0,id/0,name/0]).



%% returns type code
tc() -> {tk_struct,"IDL:omg.org/DsLogAdmin/AvailabilityStatus:1.0",
                   "AvailabilityStatus",
                   [{"off_duty",tk_boolean},{"log_full",tk_boolean}]}.

%% returns id
id() -> "IDL:omg.org/DsLogAdmin/AvailabilityStatus:1.0".

%% returns name
name() -> "DsLogAdmin_AvailabilityStatus".



