%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: DsLogAdmin
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module('DsLogAdmin').
-ic_compiled("4_2_25").


%% Interface functions
-export([default_grammar/0, wrap/0, halt/0]).
-export(['Sunday'/0, 'Monday'/0, 'Tuesday'/0]).
-export(['Wednesday'/0, 'Thursday'/0, 'Friday'/0]).
-export(['Saturday'/0, 'QoSNone'/0, 'QoSFlush'/0]).
-export(['QoSReliability'/0]).

%%%% Constant: default_grammar
%%
default_grammar() -> "EXTENDED_TCL".

%%%% Constant: wrap
%%
wrap() -> 0.

%%%% Constant: halt
%%
halt() -> 1.

%%%% Constant: 'Sunday'
%%
'Sunday'() -> 1.

%%%% Constant: 'Monday'
%%
'Monday'() -> 2.

%%%% Constant: 'Tuesday'
%%
'Tuesday'() -> 4.

%%%% Constant: 'Wednesday'
%%
'Wednesday'() -> 8.

%%%% Constant: 'Thursday'
%%
'Thursday'() -> 16.

%%%% Constant: 'Friday'
%%
'Friday'() -> 32.

%%%% Constant: 'Saturday'
%%
'Saturday'() -> 64.

%%%% Constant: 'QoSNone'
%%
'QoSNone'() -> 0.

%%%% Constant: 'QoSFlush'
%%
'QoSFlush'() -> 1.

%%%% Constant: 'QoSReliability'
%%
'QoSReliability'() -> 2.

