%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_DsLogAdmin
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_DSLOGADMIN_HRL).
-define(OE_DSLOGADMIN_HRL, true).




-endif.


