%%------------------------------------------------------------
%%
%% Implementation stub file
%% 
%% Target: oe_DsLogAdmin
%% Source: /home/tgg/src/hg/tlserl/src/DsLogAdmin.idl
%% IC vsn: 4.2.25
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------

-module(oe_DsLogAdmin).
-ic_compiled("4_2_25").


-include_lib("orber/include/ifr_types.hrl").

%% Interface functions

-export([oe_register/0, oe_unregister/0, oe_get_module/5]).
-export([oe_dependency/0]).



oe_register() ->
    OE_IFR = orber_ifr:find_repository(),

    register_tests(OE_IFR),

    _OE_1 = oe_get_top_module(OE_IFR, "IDL:omg.org/DsLogAdmin:1.0", "DsLogAdmin", "1.0"),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidParam:1.0", "InvalidParam", "1.0", [#structmember{name="details", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}]),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidThreshold:1.0", "InvalidThreshold", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidTime:1.0", "InvalidTime", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidTimeInterval:1.0", "InvalidTimeInterval", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidMask:1.0", "InvalidMask", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/LogIdAlreadyExists:1.0", "LogIdAlreadyExists", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidGrammar:1.0", "InvalidGrammar", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidConstraint:1.0", "InvalidConstraint", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/LogFull:1.0", "LogFull", "1.0", [#structmember{name="n_records_written", type=tk_short, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_short)}]),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/LogOffDuty:1.0", "LogOffDuty", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/LogLocked:1.0", "LogLocked", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/LogDisabled:1.0", "LogDisabled", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidRecordId:1.0", "InvalidRecordId", "1.0", []),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidAttribute:1.0", "InvalidAttribute", "1.0", [#structmember{name="attr_name", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}, #structmember{name="value", type=tk_any, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_any)}]),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/InvalidLogFullAction:1.0", "InvalidLogFullAction", "1.0", []),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/LogId:1.0", "LogId", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong)),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/RecordId:1.0", "RecordId", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong)),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/RecordIdList:1.0", "RecordIdList", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ulonglong,0})),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/default_grammar:1.0", "default_grammar", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), {{tk_string,0},
                                                                 "EXTENDED_TCL"}),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/Constraint:1.0", "Constraint", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/TimeT:1.0", "TimeT", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong)),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:omg.org/DsLogAdmin/NVPair:1.0", "NVPair", "1.0", [#structmember{name="name", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0})}, #structmember{name="value", type=tk_any, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_any)}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/NVList:1.0", "NVList", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                "NVPair",
                                                [{"name",{tk_string,0}},
                                                 {"value",tk_any}]},
                                               0})),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:omg.org/DsLogAdmin/TimeInterval:1.0", "TimeInterval", "1.0", [#structmember{name="start", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong)}, #structmember{name="stop", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong)}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/TimeIntervalSeq:1.0", "TimeIntervalSeq", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/TimeInterval:1.0",
                                                "TimeInterval",
                                                [{"start",tk_ulonglong},
                                                 {"stop",tk_ulonglong}]},
                                               0})),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:omg.org/DsLogAdmin/LogRecord:1.0", "LogRecord", "1.0", [#structmember{name="id", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong)}, #structmember{name="time", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong)}, #structmember{name="attr_list", type={tk_sequence,
                                      {tk_struct,
                                       "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                       "NVPair",
                                       [{"name",{tk_string,0}},
                                        {"value",tk_any}]},
                                      0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                "NVPair",
                                                [{"name",{tk_string,0}},
                                                 {"value",tk_any}]},
                                               0})}, #structmember{name="info", type=tk_any, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_any)}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/RecordList:1.0", "RecordList", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/LogRecord:1.0",
                                                "LogRecord",
                                                [{"id",tk_ulonglong},
                                                 {"time",tk_ulonglong},
                                                 {"attr_list",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                    "NVPair",
                                                    [{"name",{tk_string,0}},
                                                     {"value",tk_any}]},
                                                   0}},
                                                 {"info",tk_any}]},
                                               0})),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/Anys:1.0", "Anys", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_any,0})),

    _OE_2 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:omg.org/DsLogAdmin/Iterator:1.0", "Iterator", "1.0", []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:omg.org/DsLogAdmin/Iterator/get:1.0", "get", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/LogRecord:1.0",
                                                "LogRecord",
                                                [{"id",tk_ulonglong},
                                                 {"time",tk_ulonglong},
                                                 {"attr_list",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                    "NVPair",
                                                    [{"name",{tk_string,0}},
                                                     {"value",tk_any}]},
                                                   0}},
                                                 {"info",tk_any}]},
                                               0}), 'OP_NORMAL', [#parameterdescription{name="how_many", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
, #parameterdescription{name="position", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidParam:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_2, "IDL:omg.org/DsLogAdmin/Iterator/destroy:1.0", "destroy", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [], [], []),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:omg.org/DsLogAdmin/AvailabilityStatus:1.0", "AvailabilityStatus", "1.0", [#structmember{name="off_duty", type=tk_boolean, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_boolean)}, #structmember{name="log_full", type=tk_boolean, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_boolean)}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/LogFullActionType:1.0", "LogFullActionType", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort)),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/wrap:1.0", "wrap", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,0}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/halt:1.0", "halt", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,1}),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:omg.org/DsLogAdmin/Time24:1.0", "Time24", "1.0", [#structmember{name="hour", type=tk_ushort, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort)}, #structmember{name="minute", type=tk_ushort, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort)}]),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:omg.org/DsLogAdmin/Time24Interval:1.0", "Time24Interval", "1.0", [#structmember{name="start", type={tk_struct,
                                     "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                     "Time24",
                                     [{"hour",tk_ushort},
                                      {"minute",tk_ushort}]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                               "Time24",
                                               [{"hour",tk_ushort},
                                                {"minute",tk_ushort}]})}, #structmember{name="stop", type={tk_struct,
                                    "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                    "Time24",
                                    [{"hour",tk_ushort},{"minute",tk_ushort}]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                               "Time24",
                                               [{"hour",tk_ushort},
                                                {"minute",tk_ushort}]})}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/IntervalsOfDay:1.0", "IntervalsOfDay", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/Time24Interval:1.0",
                                                "Time24Interval",
                                                [{"start",
                                                  {tk_struct,
                                                   "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                   "Time24",
                                                   [{"hour",tk_ushort},
                                                    {"minute",tk_ushort}]}},
                                                 {"stop",
                                                  {tk_struct,
                                                   "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                   "Time24",
                                                   [{"hour",tk_ushort},
                                                    {"minute",tk_ushort}]}}]},
                                               0})),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/Sunday:1.0", "Sunday", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,1}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/Monday:1.0", "Monday", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,2}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/Tuesday:1.0", "Tuesday", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,4}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/Wednesday:1.0", "Wednesday", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,8}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/Thursday:1.0", "Thursday", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,16}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/Friday:1.0", "Friday", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,32}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/Saturday:1.0", "Saturday", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,64}),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/DaysOfWeek:1.0", "DaysOfWeek", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort)),

    orber_ifr:'ModuleDef_create_struct'(_OE_1, "IDL:omg.org/DsLogAdmin/WeekMaskItem:1.0", "WeekMaskItem", "1.0", [#structmember{name="days", type=tk_ushort, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort)}, #structmember{name="intervals", type={tk_sequence,
                                      {tk_struct,
                                       "IDL:omg.org/DsLogAdmin/Time24Interval:1.0",
                                       "Time24Interval",
                                       [{"start",
                                         {tk_struct,
                                          "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                          "Time24",
                                          [{"hour",tk_ushort},
                                           {"minute",tk_ushort}]}},
                                        {"stop",
                                         {tk_struct,
                                          "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                          "Time24",
                                          [{"hour",tk_ushort},
                                           {"minute",tk_ushort}]}}]},
                                      0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/Time24Interval:1.0",
                                                "Time24Interval",
                                                [{"start",
                                                  {tk_struct,
                                                   "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                   "Time24",
                                                   [{"hour",tk_ushort},
                                                    {"minute",tk_ushort}]}},
                                                 {"stop",
                                                  {tk_struct,
                                                   "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                   "Time24",
                                                   [{"hour",tk_ushort},
                                                    {"minute",tk_ushort}]}}]},
                                               0})}]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/WeekMask:1.0", "WeekMask", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/WeekMaskItem:1.0",
                                                "WeekMaskItem",
                                                [{"days",tk_ushort},
                                                 {"intervals",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/Time24Interval:1.0",
                                                    "Time24Interval",
                                                    [{"start",
                                                      {tk_struct,
                                                       "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                       "Time24",
                                                       [{"hour",tk_ushort},
                                                        {"minute",
                                                         tk_ushort}]}},
                                                     {"stop",
                                                      {tk_struct,
                                                       "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                       "Time24",
                                                       [{"hour",tk_ushort},
                                                        {"minute",
                                                         tk_ushort}]}}]},
                                                   0}}]},
                                               0})),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/Threshold:1.0", "Threshold", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort)),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/CapacityAlarmThresholdList:1.0", "CapacityAlarmThresholdList", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ushort,0})),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:omg.org/DsLogAdmin/OperationalState:1.0", "OperationalState", "1.0", ["disabled","enabled"]),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:omg.org/DsLogAdmin/AdministrativeState:1.0", "AdministrativeState", "1.0", ["locked","unlocked"]),

    orber_ifr:'ModuleDef_create_enum'(_OE_1, "IDL:omg.org/DsLogAdmin/ForwardingState:1.0", "ForwardingState", "1.0", ["on","off"]),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/QoSType:1.0", "QoSType", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort)),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/QoSList:1.0", "QoSList", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ushort,0})),

    orber_ifr:'ModuleDef_create_exception'(_OE_1, "IDL:omg.org/DsLogAdmin/UnsupportedQoS:1.0", "UnsupportedQoS", "1.0", [#structmember{name="denied", type={tk_sequence,tk_ushort,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ushort,0})}]),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/QoSNone:1.0", "QoSNone", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,0}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/QoSFlush:1.0", "QoSFlush", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,1}),

    orber_ifr:'ModuleDef_create_constant'(_OE_1, "IDL:omg.org/DsLogAdmin/QoSReliability:1.0", "QoSReliability", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), {tk_ushort,2}),

    _OE_3 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:omg.org/DsLogAdmin/Log:1.0", "Log", "1.0", []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/my_factory:1.0", "my_factory", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/LogMgr:1.0",
                                               "LogMgr"}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/id:1.0", "id", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_log_qos:1.0", "get_log_qos", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ushort,0}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_log_qos:1.0", "set_log_qos", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="qos", type={tk_sequence,tk_ushort,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ushort,0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/UnsupportedQoS:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_max_record_life:1.0", "get_max_record_life", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_max_record_life:1.0", "set_max_record_life", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="life", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_max_size:1.0", "get_max_size", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_max_size:1.0", "set_max_size", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="size", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidParam:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_current_size:1.0", "get_current_size", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_n_records:1.0", "get_n_records", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_log_full_action:1.0", "get_log_full_action", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_log_full_action:1.0", "set_log_full_action", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="action", type=tk_ushort, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidLogFullAction:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_administrative_state:1.0", "get_administrative_state", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:omg.org/DsLogAdmin/AdministrativeState:1.0",
                                               "AdministrativeState",
                                               ["locked","unlocked"]}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_administrative_state:1.0", "set_administrative_state", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="state", type={tk_enum,
                                          "IDL:omg.org/DsLogAdmin/AdministrativeState:1.0",
                                          "AdministrativeState",
                                          ["locked","unlocked"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:omg.org/DsLogAdmin/AdministrativeState:1.0",
                                               "AdministrativeState",
                                               ["locked","unlocked"]}), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_forwarding_state:1.0", "get_forwarding_state", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:omg.org/DsLogAdmin/ForwardingState:1.0",
                                               "ForwardingState",
                                               ["on","off"]}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_forwarding_state:1.0", "set_forwarding_state", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="state", type={tk_enum,
                                          "IDL:omg.org/DsLogAdmin/ForwardingState:1.0",
                                          "ForwardingState",
                                          ["on","off"]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:omg.org/DsLogAdmin/ForwardingState:1.0",
                                               "ForwardingState",
                                               ["on","off"]}), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_operational_state:1.0", "get_operational_state", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_enum,
                                               "IDL:omg.org/DsLogAdmin/OperationalState:1.0",
                                               "OperationalState",
                                               ["disabled","enabled"]}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_interval:1.0", "get_interval", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/TimeInterval:1.0",
                                               "TimeInterval",
                                               [{"start",tk_ulonglong},
                                                {"stop",tk_ulonglong}]}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_interval:1.0", "set_interval", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="interval", type={tk_struct,
                                             "IDL:omg.org/DsLogAdmin/TimeInterval:1.0",
                                             "TimeInterval",
                                             [{"start",tk_ulonglong},
                                              {"stop",tk_ulonglong}]}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/TimeInterval:1.0",
                                               "TimeInterval",
                                               [{"start",tk_ulonglong},
                                                {"stop",tk_ulonglong}]}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidTimeInterval:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidTime:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_availability_status:1.0", "get_availability_status", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/AvailabilityStatus:1.0",
                                               "AvailabilityStatus",
                                               [{"off_duty",tk_boolean},
                                                {"log_full",tk_boolean}]}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_capacity_alarm_thresholds:1.0", "get_capacity_alarm_thresholds", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ushort,0}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_capacity_alarm_thresholds:1.0", "set_capacity_alarm_thresholds", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="threshs", type={tk_sequence,tk_ushort,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ushort,0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidThreshold:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_week_mask:1.0", "get_week_mask", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/WeekMaskItem:1.0",
                                                "WeekMaskItem",
                                                [{"days",tk_ushort},
                                                 {"intervals",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/Time24Interval:1.0",
                                                    "Time24Interval",
                                                    [{"start",
                                                      {tk_struct,
                                                       "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                       "Time24",
                                                       [{"hour",tk_ushort},
                                                        {"minute",
                                                         tk_ushort}]}},
                                                     {"stop",
                                                      {tk_struct,
                                                       "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                       "Time24",
                                                       [{"hour",tk_ushort},
                                                        {"minute",
                                                         tk_ushort}]}}]},
                                                   0}}]},
                                               0}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_week_mask:1.0", "set_week_mask", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="masks", type={tk_sequence,
                                          {tk_struct,
                                           "IDL:omg.org/DsLogAdmin/WeekMaskItem:1.0",
                                           "WeekMaskItem",
                                           [{"days",tk_ushort},
                                            {"intervals",
                                             {tk_sequence,
                                              {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/Time24Interval:1.0",
                                               "Time24Interval",
                                               [{"start",
                                                 {tk_struct,
                                                  "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                  "Time24",
                                                  [{"hour",tk_ushort},
                                                   {"minute",tk_ushort}]}},
                                                {"stop",
                                                 {tk_struct,
                                                  "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                  "Time24",
                                                  [{"hour",tk_ushort},
                                                   {"minute",tk_ushort}]}}]},
                                              0}}]},
                                          0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/WeekMaskItem:1.0",
                                                "WeekMaskItem",
                                                [{"days",tk_ushort},
                                                 {"intervals",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/Time24Interval:1.0",
                                                    "Time24Interval",
                                                    [{"start",
                                                      {tk_struct,
                                                       "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                       "Time24",
                                                       [{"hour",tk_ushort},
                                                        {"minute",
                                                         tk_ushort}]}},
                                                     {"stop",
                                                      {tk_struct,
                                                       "IDL:omg.org/DsLogAdmin/Time24:1.0",
                                                       "Time24",
                                                       [{"hour",tk_ushort},
                                                        {"minute",
                                                         tk_ushort}]}}]},
                                                   0}}]},
                                               0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidMask:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidTimeInterval:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidTime:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/query:1.0", "query", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/LogRecord:1.0",
                                                "LogRecord",
                                                [{"id",tk_ulonglong},
                                                 {"time",tk_ulonglong},
                                                 {"attr_list",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                    "NVPair",
                                                    [{"name",{tk_string,0}},
                                                     {"value",tk_any}]},
                                                   0}},
                                                 {"info",tk_any}]},
                                               0}), 'OP_NORMAL', [#parameterdescription{name="i", type={tk_objref,
                                      "IDL:omg.org/DsLogAdmin/Iterator:1.0",
                                      "Iterator"}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/Iterator:1.0",
                                               "Iterator"}), mode='PARAM_OUT'}
, #parameterdescription{name="c", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
, #parameterdescription{name="grammar", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidConstraint:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidGrammar:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/retrieve:1.0", "retrieve", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/LogRecord:1.0",
                                                "LogRecord",
                                                [{"id",tk_ulonglong},
                                                 {"time",tk_ulonglong},
                                                 {"attr_list",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                    "NVPair",
                                                    [{"name",{tk_string,0}},
                                                     {"value",tk_any}]},
                                                   0}},
                                                 {"info",tk_any}]},
                                               0}), 'OP_NORMAL', [#parameterdescription{name="i", type={tk_objref,
                                      "IDL:omg.org/DsLogAdmin/Iterator:1.0",
                                      "Iterator"}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/Iterator:1.0",
                                               "Iterator"}), mode='PARAM_OUT'}
, #parameterdescription{name="how_many", type=tk_long, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_long), mode='PARAM_IN'}
, #parameterdescription{name="from_time", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/match:1.0", "match", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [#parameterdescription{name="c", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
, #parameterdescription{name="grammar", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidConstraint:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidGrammar:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/delete_records:1.0", "delete_records", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [#parameterdescription{name="c", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
, #parameterdescription{name="grammar", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidConstraint:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidGrammar:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/delete_records_by_id:1.0", "delete_records_by_id", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [#parameterdescription{name="ids", type={tk_sequence,tk_ulonglong,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ulonglong,0}), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/write_records:1.0", "write_records", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="records", type={tk_sequence,tk_any,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_any,0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogDisabled:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogLocked:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogOffDuty:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogFull:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/write_recordlist:1.0", "write_recordlist", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="list", type={tk_sequence,
                                         {tk_struct,
                                          "IDL:omg.org/DsLogAdmin/LogRecord:1.0",
                                          "LogRecord",
                                          [{"id",tk_ulonglong},
                                           {"time",tk_ulonglong},
                                           {"attr_list",
                                            {tk_sequence,
                                             {tk_struct,
                                              "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                              "NVPair",
                                              [{"name",{tk_string,0}},
                                               {"value",tk_any}]},
                                             0}},
                                           {"info",tk_any}]},
                                         0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/LogRecord:1.0",
                                                "LogRecord",
                                                [{"id",tk_ulonglong},
                                                 {"time",tk_ulonglong},
                                                 {"attr_list",
                                                  {tk_sequence,
                                                   {tk_struct,
                                                    "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                    "NVPair",
                                                    [{"name",{tk_string,0}},
                                                     {"value",tk_any}]},
                                                   0}},
                                                 {"info",tk_any}]},
                                               0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogDisabled:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogLocked:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogOffDuty:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogFull:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_record_attribute:1.0", "set_record_attribute", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [#parameterdescription{name="attr_list", type={tk_sequence,
                                              {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                               "NVPair",
                                               [{"name",{tk_string,0}},
                                                {"value",tk_any}]},
                                              0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                "NVPair",
                                                [{"name",{tk_string,0}},
                                                 {"value",tk_any}]},
                                               0}), mode='PARAM_IN'}
, #parameterdescription{name="id", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidAttribute:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidRecordId:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/set_records_attribute:1.0", "set_records_attribute", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), 'OP_NORMAL', [#parameterdescription{name="attr_list", type={tk_sequence,
                                              {tk_struct,
                                               "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                               "NVPair",
                                               [{"name",{tk_string,0}},
                                                {"value",tk_any}]},
                                              0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                "NVPair",
                                                [{"name",{tk_string,0}},
                                                 {"value",tk_any}]},
                                               0}), mode='PARAM_IN'}
, #parameterdescription{name="c", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
, #parameterdescription{name="grammar", type={tk_string,0}, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_string,0}), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidAttribute:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidConstraint:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidGrammar:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/get_record_attribute:1.0", "get_record_attribute", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_struct,
                                                "IDL:omg.org/DsLogAdmin/NVPair:1.0",
                                                "NVPair",
                                                [{"name",{tk_string,0}},
                                                 {"value",tk_any}]},
                                               0}), 'OP_NORMAL', [#parameterdescription{name="id", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidRecordId:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/copy:1.0", "copy", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/Log:1.0",
                                               "Log"}), 'OP_NORMAL', [#parameterdescription{name="id", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_OUT'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/copy_with_id:1.0", "copy_with_id", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/Log:1.0",
                                               "Log"}), 'OP_NORMAL', [#parameterdescription{name="id", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogIdAlreadyExists:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_3, "IDL:omg.org/DsLogAdmin/Log/flush:1.0", "flush", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/UnsupportedQoS:1.0")], []),

    _OE_4 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:omg.org/DsLogAdmin/BasicLog:1.0", "BasicLog", "1.0", [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/Log:1.0")]),

    orber_ifr:'InterfaceDef_create_operation'(_OE_4, "IDL:omg.org/DsLogAdmin/BasicLog/destroy:1.0", "destroy", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, tk_void), 'OP_NORMAL', [], [], []),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/LogList:1.0", "LogList", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_objref,
                                                "IDL:omg.org/DsLogAdmin/Log:1.0",
                                                "Log"},
                                               0})),

    orber_ifr:'ModuleDef_create_alias'(_OE_1, "IDL:omg.org/DsLogAdmin/LogIdList:1.0", "LogIdList", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ulong,0})),

    _OE_5 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:omg.org/DsLogAdmin/LogMgr:1.0", "LogMgr", "1.0", []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_5, "IDL:omg.org/DsLogAdmin/LogMgr/list_logs:1.0", "list_logs", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,
                                               {tk_objref,
                                                "IDL:omg.org/DsLogAdmin/Log:1.0",
                                                "Log"},
                                               0}), 'OP_NORMAL', [], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_5, "IDL:omg.org/DsLogAdmin/LogMgr/find_log:1.0", "find_log", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/Log:1.0",
                                               "Log"}), 'OP_NORMAL', [#parameterdescription{name="id", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
], [], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_5, "IDL:omg.org/DsLogAdmin/LogMgr/list_logs_by_id:1.0", "list_logs_by_id", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_sequence,tk_ulong,0}), 'OP_NORMAL', [], [], []),

    _OE_6 = orber_ifr:'ModuleDef_create_interface'(_OE_1, "IDL:omg.org/DsLogAdmin/BasicLogFactory:1.0", "BasicLogFactory", "1.0", [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogMgr:1.0")]),

    orber_ifr:'InterfaceDef_create_operation'(_OE_6, "IDL:omg.org/DsLogAdmin/BasicLogFactory/create:1.0", "create", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/BasicLog:1.0",
                                               "BasicLog"}), 'OP_NORMAL', [#parameterdescription{name="id", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_OUT'}
, #parameterdescription{name="max_size", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), mode='PARAM_IN'}
, #parameterdescription{name="full_action", type=tk_ushort, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidLogFullAction:1.0")], []),

    orber_ifr:'InterfaceDef_create_operation'(_OE_6, "IDL:omg.org/DsLogAdmin/BasicLogFactory/create_with_id:1.0", "create_with_id", "1.0", orber_ifr:'Repository_create_idltype'(OE_IFR, {tk_objref,
                                               "IDL:omg.org/DsLogAdmin/BasicLog:1.0",
                                               "BasicLog"}), 'OP_NORMAL', [#parameterdescription{name="max_size", type=tk_ulonglong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulonglong), mode='PARAM_IN'}
, #parameterdescription{name="full_action", type=tk_ushort, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ushort), mode='PARAM_IN'}
, #parameterdescription{name="id", type=tk_ulong, type_def=orber_ifr:'Repository_create_idltype'(OE_IFR, tk_ulong), mode='PARAM_IN'}
], [orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidLogFullAction:1.0"), orber_ifr:lookup_id(OE_IFR,"IDL:omg.org/DsLogAdmin/LogIdAlreadyExists:1.0")], []),

    ok.


%% General IFR registration checks.
register_tests(OE_IFR)->
  re_register_test(OE_IFR),
  include_reg_test(OE_IFR).


%% IFR type Re-registration checks.
re_register_test(OE_IFR)->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:omg.org/DsLogAdmin/InvalidParam:1.0") of
    []  ->
      true;
    _ ->
      exit({allready_registered,"IDL:omg.org/DsLogAdmin/InvalidParam:1.0"})
 end.


%% IFR registration checks for included idl files.
include_reg_test(OE_IFR) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR,"IDL:omg.org/TimeBase:1.0") of
    [] ->
      exit({unregistered,"IDL:omg.org/TimeBase:1.0"});
    _  ->
      true
  end,
  true.


%% Fetch top module reference, register if unregistered.
oe_get_top_module(OE_IFR, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'Repository_create_module'(OE_IFR, ID, Name, Version);
    Mod  ->
      Mod
   end.

%% Fetch module reference, register if unregistered.
oe_get_module(OE_IFR, OE_Parent, ID, Name, Version) ->
  case orber_ifr:'Repository_lookup_id'(OE_IFR, ID) of
    [] ->
      orber_ifr:'ModuleDef_create_module'(OE_Parent, ID, Name, Version);
    Mod  ->
      Mod
   end.



oe_unregister() ->
    OE_IFR = orber_ifr:find_repository(),

    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/BasicLogFactory:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogMgr:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogIdList:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogList:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/BasicLog:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Log:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/QoSReliability:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/QoSFlush:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/QoSNone:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/UnsupportedQoS:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/QoSList:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/QoSType:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/ForwardingState:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/AdministrativeState:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/OperationalState:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/CapacityAlarmThresholdList:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Threshold:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/WeekMask:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/WeekMaskItem:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/DaysOfWeek:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Saturday:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Friday:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Thursday:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Wednesday:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Tuesday:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Monday:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Sunday:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/IntervalsOfDay:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Time24Interval:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Time24:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/halt:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/wrap:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogFullActionType:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/AvailabilityStatus:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Iterator:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Anys:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/RecordList:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogRecord:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/TimeIntervalSeq:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/TimeInterval:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/NVList:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/NVPair:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/TimeT:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/Constraint:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/default_grammar:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/RecordIdList:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/RecordId:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogId:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidLogFullAction:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidAttribute:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidRecordId:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogDisabled:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogLocked:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogOffDuty:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogFull:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidConstraint:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidGrammar:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/LogIdAlreadyExists:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidMask:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidTimeInterval:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidTime:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidThreshold:1.0"),
    oe_destroy(OE_IFR, "IDL:omg.org/DsLogAdmin/InvalidParam:1.0"),
    oe_destroy_if_empty(OE_IFR, "IDL:omg.org/DsLogAdmin:1.0"),
    ok.


oe_destroy_if_empty(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    case orber_ifr:contents(Ref, 'dk_All', 'true') of
		[] ->
		    orber_ifr:destroy(Ref),
		    ok;
		_ ->
		    ok
	    end
    end.

oe_destroy(OE_IFR,IFR_ID) ->
    case orber_ifr:'Repository_lookup_id'(OE_IFR, IFR_ID) of
	[] ->
	    ok;
	Ref ->
	    orber_ifr:destroy(Ref),
	    ok
    end.



%% Idl file dependency list function
oe_dependency() ->

    {"/home/tgg/src/hg/tlserl/src/DsLogAdmin.idl",["TimeBase.idl"]}.

